version: "3.7"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.1
    container_name: elasticsearch-goornella
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=pw
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
      - xpack.security.enabled=false 
      - cluster.routing.allocation.disk.threshold_enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:8.9.1
    container_name: kibana-goornella
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_PASSWORD=pw
    ports:
      - "5601:5601"
    volumes:
      - ./kibana/data:/usr/share/kibana/data
    networks:
      - elastic
    depends_on:
      - elasticsearch


  app:
    build: .
    container_name: goornella_app
    ports:
      - "5001:5001"
    depends_on:
      - elasticsearch
    networks:
      - elastic
    expose:
      - "5001"



volumes:
  esdata:
    driver: local

networks:
  elastic:
    driver: bridge